# ============================================================================
# fitSurvCox.R – General purpose survival‑analysis wrapper
# -----------------------------------------------------------------------------
# Author: Auto‑generated by ChatGPT (OpenAI o3) – July 2025
# Licence: MIT
#
# This single function consolidates all logic discussed in the user’s MATLAB
# wrapper and R helper script into a reusable, fully‑documented R interface.
# It supports:
#   • Alternate time scales (TTE vs AOO)
#   • Optional left‑truncation (delayed entry)
#   • Exclusion of prevalent cases and landmark filtering
#   • Multiple predictors analysed one‑at‑a‑time (e.g. GWAS SNPs)
#   • Optional time‑varying covariate (single variable supplied as long format)
#   • Cause‑specific Cox, Fine‑Gray (crr / fastcrr), KM, CIF with percentile‑
#     bootstrap CIs, reverse‑KM median follow‑up, diagnostics (PH tests & plots)
#   • Publication‑ready PDF output (plots) & tidy data frames (metrics)
#
# Dependencies (all CRAN): survival, dplyr, tibble, broom, survminer,
#   ggsurvfit, tidycmprsk, riskRegression, fastcmprsk, prodlim, finalfit,
#   psclBAR, data.table, pbapply, ggplot2
#
# -----------------------------------------------------------------------------
#' @title General‑purpose Survival Analysis with Multiple Time Scales & TVCs
#' @description Fits uni‑ and multivariable Cox models (cause‑specific and
#' optionally sub‑distribution), generates KM/CIF plots, diagnostics, reverse‑
#' Kaplan–Meier median follow‑up and assorted metrics for each predictor.
#'
#' @param df          A wide data.frame containing one row per subject with
#'                    time variables `tt`, `tt0`, status code (`censor`) and
#'                    predictors / baseline covariates. If `tv_df` is NULL the
#'                    column `eid` is *optional* and ignored.
#' @param preds       Character vector of *baseline* predictor column names –
#'                    each will be analysed separately. (E.g. SNPs.)
#' @param covars      Character vector of additional baseline covariate column
#'                    names. May be empty (default).
#' @param tv_df       *Optional* long‑format data.frame holding a **single**
#'                    time‑varying covariate (TVC). Required columns:
#'                    • `eid` – subject identifier matching `df$eid`
#'                    • `start`, `stop` – interval start & stop times on the
#'                      *same* scale used in `df` (see Details)
#'                    • `value` – numeric/ factor levels for the covariate
#'                    • `name` – a character column; only `name[1]` is used to
#'                      label the variable.
#'                    Observations for subjects without the TVC can be absent –
#'                    they are assumed to have a constant default value (0 or
#'                    NA) over follow‑up and are handled internally.
#' @param timeOrigin  Either "TTE" (default) or "AOO". Determines how `tt` and
#'                    `tt0` are interpreted (see Details).
#' @param LT          Logical. If TRUE, left‑truncation is applied using
#'                    delayed‑entry argument order described in Details.
#' @param prevalent   Logical. If FALSE (default) prevalent cases (diagnosed
#'                    before study entry) are dropped – see logic table in
#'                    vignette.
#' @param landmark    Numeric ≥ 0. Optional landmark (years) – subjects with a
#'                    non‑zero status and `tt ≤ landmark` are excluded *before*
#'                    further processing. Ignored when 0.
#' @param FGR         Character. "none" (default), "crr" or "fastcrr" for Fine–
#'                    Gray subdistribution models.
#' @param plot        Logical. If TRUE (default) PDF plots are produced in
#'                    `outDir`.
#' @param diag        Logical. If TRUE (default) proportional‑hazards
#'                    diagnostics are run and saved.
#' @param outDir      Output directory (string). Defaults to working dir.
#' @param seed        Integer random‑seed for bootstrap CIs (default 1).
#' @param nBoot       Integer bootstrap replicates for CIF CIs (default 500).
#' @details
#' *Time scales*
#'   • **TTE** (Time‑to‑Event): `tt` is the forward time scale. If `LT = TRUE`
#'     then `tt0` supplies delayed entry (time since diagnosis), yielding
#'     `Surv(tt0, tt, …, type = "counting")`.
#'   • **AOO** (Age‑of‑Onset): `tt0` is age‑at‑onset. With `LT = TRUE`, `tt`
#'     holds entry age and analysis uses `Surv(tt, tt0, …, type = "counting")`.
#'
#' A compact cross‑tab of argument combinations is reproduced in the user’s
#' spec. Rows with negative or zero time are *always* discarded.
#'
#' *Status codes*
#'   • 0 – censored after last contact
#'   • 1 – event of interest
#'   • 2 – death before event (competing)
#'   • 3 – other competing cause
#'
#' *Time‑varying covariate* (`tv_df`)
#'   The helper `.merge_tvc()` converts `tv_df` to counting‑process style via
#'   `survival::tmerge`, merges it back into `df`, and returns an appropriately
#'   duplicated dataset. This supports either binary switches (e.g. therapy on
#'   off) or continuous measures (e.g. BMI trajectories). Continuous values are
#'   assumed piece‑wise constant between measurements; update strategy can be
#'   controlled with `tvc_method` ("locf" | "nocb" | "linear" placeholder).
#'
#' @return A named list with:
#'   • `results` – tidy table (one row per predictor) with HR / aHR / sHR,
#'     CIs, p‑values and model metrics.
#'   • `followUp` – median follow‑up estimate (reverse KM).
#'   • `km_fit`, `cif_fit` – lists of survfit / prodlim objects (invisibly).
#'   • Invisibly: file paths of generated PDFs.
#'
#' @examples
#' ## 1 – AOO with left‑truncation (no TVC)
#' data <- data.frame(eid = 1:4,
#'                    tt0 = c(12,15, 8,20),
#'                    tt  = c(10,10, 5,15),
#'                    censor = c(1,0,0,1),
#'                    SNP1 = c(0,1,0,2),
#'                    Sex = factor(c("M","F","F","M")))
#' fit <- fitSurvCox(data, preds = "SNP1", covars = "Sex",
#'                   timeOrigin = "AOO", LT = TRUE)
#'
#' ## 2 – TTE with a binary therapy TVC
#' tv <- data.frame(eid   = c(1,1,2,2,2,3),
#'                 start = c(0, 5, 0, 3, 8, 0),
#'                 stop  = c(5,10, 3, 8,12,12),
#'                 value = c(0, 1, 0, 1, 1, 0),
#'                 name  = "Therapy")
#' fit2 <- fitSurvCox(dataTTE, preds = c("SNP1","SNP2"),
#'                    covars = c("Age","Sex"), tv_df = tv,
#'                    timeOrigin = "TTE", LT = FALSE, FGR = "crr")
#'
# -----------------------------------------------------------------------------
fitSurvCox <- function(df, preds, covars = NULL,
                       tv_df = NULL,
                       timeOrigin = c("TTE", "AOO"),
                       LT = FALSE, prevalent = FALSE, landmark = 0,
                       FGR = c("none", "crr", "fastcrr"),
                       plot = TRUE, diag = TRUE,
                       outDir = getwd(), seed = 1L, nBoot = 500L) {
  # ---- 0. Prep & checks ------------------------------------------------------
  stopifnot(is.data.frame(df), is.character(preds))
  timeOrigin <- match.arg(timeOrigin)
  FGR        <- match.arg(FGR)
  if (!is.null(covars) && !is.character(covars))
    stop("`covars` must be character vector or NULL")
  if (!is.null(tv_df) && is.null(df$eid))
    stop("`df` must contain an `eid` column when a time‑varying covariate is supplied")
  dir.create(outDir, showWarnings = FALSE, recursive = TRUE)
  set.seed(seed)
  
  # ---- 1. Handle landmark & prevalent filters ------------------------------
  if (landmark > 0) {
    idx_drop <- df$censor != 0 & df$tt <= landmark
    df <- df[!idx_drop, ]
  }
  if (!prevalent && "base" %in% names(df)) {
    df <- df[df$base <= 0, ]
    df$base <- NULL
  }
  
  # ---- 2. Remove invalid/negative follow‑up --------------------------------
  if (timeOrigin == "TTE") {
    idx <- df$tt < 0
  } else { # AOO
    idx <- df$tt <= 0
  }
  if (any(idx)) df <- df[!idx, ]
  
  # ---- 3. Left‑truncation alignment ----------------------------------------
  if (LT) {
    if (timeOrigin == "TTE") {
      entry_col <- "tt0"; exit_col <- "tt"
    } else {
      entry_col <- "tt" ; exit_col <- "tt0"
      df[[entry_col]] <- df[[exit_col]] - df[[entry_col]]  # convert to gap time
    }
  } else {
    entry_col <- NULL; exit_col <- "tt"
  }
  
  # ---- 4. Merge time‑varying covariate -------------------------------------
  if (!is.null(tv_df)) {
    df <- .merge_tvc(df, tv_df, entry = entry_col, exit = exit_col, timeOrigin)
    # columns `tstart`, `tstop` now exist; override entry/exit for analysis
    entry_col <- "tstart"; exit_col <- "tstop"
  }
  
  # ---- 5. Reverse‑KM median follow‑up --------------------------------------
  if (LT) {
    surv_obj_mf <- survival::Surv(df[[entry_col]], df[[exit_col]], df$censor == 0, type = "counting")
  } else {
    surv_obj_mf <- survival::Surv(df[[exit_col]], df$censor == 0)
  }
  mf <- survminer::surv_median(survival::survfit(surv_obj_mf ~ 1, data = df))
  
  # ---- 6. Helper fns --------------------------------------------------------
  .pruneStab <- function(f, tag, flag = 0) {
    s <- summary(f, digits = 3)
    out <- as.data.frame(cbind(s$coef, s$conf.int))
    if (flag == 0)
      keep <- c("exp(coef)", "se(coef)", "Pr(>|z|)", "lower .95", "upper .95")
    else if (flag == 1)
      keep <- c("exp(coef)", "se(coef)", "p-value", "2.5%", "97.5%")
    else
      keep <- c("exp(coef)", "se(coef)", "Pr(>|z|)", "2.5%", "97.5%")
    names(out)[match(keep, names(out))] <- c(tag, "SE", "P", "CIL", "CIH")
    out$CI   <- sprintf("[%.2f,%.2f]", out$CIL, out$CIH)
    out$Term <- rownames(out)
    out[, c("Term", tag, "SE", "P", "CI")]
  }
  
  .fit_cif  <- function(dat, genoCol, timeStop, entryCol, statusCol,
                        strataDF, times, causeLabel) {
    form <- as.formula(sprintf("Hist(%s,%s,entry=%s)~%s",
                               timeStop, statusCol, entryCol, genoCol))
    fit  <- prodlim::prodlim(form, data = dat)
    pred <- predict(fit, newdata = strataDF, times = times,
                    cause = causeLabel, type = "risk")
    mat  <- do.call(cbind, lapply(pred, as.numeric))
    if (is.vector(mat)) mat <- matrix(mat, ncol = 1L)
    mat
  }
  
  .cif_boot_ci <- function(df, genoCol, timeStop, entryCol, statusCol,
                           causeLabel = "event", times = NULL,
                           nBoot = nBoot, seed = seed, parallel = FALSE) {
    set.seed(seed)
    if (is.null(times)) {
      times <- sort(unique(unlist(prodlim::prodlim(
        Hist(df[[timeStop]], df[[statusCol]], entry = df[[entryCol]]) ~ 1)$time)))
    }
    strataDF <- unique(df[, genoCol, drop = FALSE])
    pointMat <- .fit_cif(df, genoCol, timeStop, entryCol, statusCol,
                         strataDF, times, causeLabel)
    bootFun <- function(idx) {
      .fit_cif(df[idx, , drop = FALSE], genoCol, timeStop, entryCol, statusCol,
               strataDF, times, causeLabel)
    }
    idxMat <- matrix(sample.int(nrow(df), nrow(df) * nBoot, TRUE), nBoot)
    bootMats <- pbapply::pblapply(seq_len(nBoot), function(b) bootFun(idxMat[b, ]))
    arr <- array(unlist(bootMats), dim = c(length(times), ncol(pointMat), nBoot))
    lowMat  <- apply(arr, 1:2, quantile, .025, na.rm = TRUE)
    highMat <- apply(arr, 1:2, quantile, .975, na.rm = TRUE)
    k <- ncol(pointMat)
    labs <- apply(strataDF, 1, paste, collapse = "_")
    data.table::data.table(time     = rep(times, k),
                           strata   = factor(rep(labs, each = length(times)), levels = labs),
                           cif      = as.numeric(pointMat),
                           cif.low  = as.numeric(lowMat),
                           cif.high = as.numeric(highMat))
  }
  
  # ---- 7. Run analysis predictor‑by‑predictor ------------------------------
  res_list <- vector("list", length(preds))
  for (i in seq_along(preds)) {
    pred <- preds[i]
    # Build Surv objects ------------------------------------------------------
    if (LT) {
      surv_cs  <- survival::Surv(df[[entry_col]], df[[exit_col]], df$censor == 1, type = "counting")
      surv_crr <- survival::Surv(df[[entry_col]], df[[exit_col]], df$censor)
    } else {
      surv_cs  <- survival::Surv(df[[exit_col]], df$censor == 1)
      surv_crr <- survival::Surv(df[[exit_col]], df$censor)
    }
    
    # Cox models --------------------------------------------------------------
    uni  <- finalfit::coxphmulti(data = df, dependent = deparse1(substitute(surv_cs)), explanatory = pred)
    expl <- c(pred, covars)
    formula_multi <- reformulate(expl, response = deparse1(substitute(surv_cs)))
    multi <- survival::coxph(formula_multi, data = df, subset = complete.cases(df[, c(expl, exit_col)]))
    
    tab0 <- .pruneStab(uni,  "HR", 0)
    tab1 <- .pruneStab(multi, "aHR", 0)
    out  <- merge(tab0, tab1, by = "Term", all = TRUE)
    
    # Fine‑Gray --------------------------------------------------------------
    if (FGR != "none") {
      if (FGR == "crr") {
        crr_fit <- riskRegression::crrmulti(formula = surv_crr ~ ., data = df[, c(pred, covars, "censor", exit_col, if (LT) entry_col)], explanatory = expl)
        tab2    <- .pruneStab(crr_fit, "sHR", 1)
      } else {
        formula_fg <- reformulate(expl, response = sprintf("Crisk(%s, censor)", exit_col))
        crr_fit <- fastcmprsk::fastCrr(formula_fg, data = df)
        tab2    <- .pruneStab(crr_fit, "sHR", 2)
        tab2$Term <- tab1$Term
      }
      out <- merge(out, tab2, by = "Term", all = TRUE)
    }
    
    out$SNP <- pred
    res_list[[i]] <- out
    
    # ---- Plots -------------------------------------------------------------
    if (plot) {
      pdf(file.path(outDir, sprintf("km.%s.%s.pdf", pred, timeOrigin)))
      if (LT) {
        km <- ggsurvfit::ggsurvfit(ggsurvfit::survfit2(surv_cs ~ df[[pred]], data = df))
      } else {
        km <- ggsurvfit::ggsurvfit(ggsurvfit::survfit2(surv_cs ~ df[[pred]], data = df))
      }
      print(km + ggsurvfit::add_confidence_interval() + labs(x = "Years", y = "Survival probability"))
      dev.off()
      
      # CIF bootstrap --------------------------------------------------------
      status_char <- factor(df$censor, levels = 0:3, labels = c("0","event","death","competing"))
      df$censor2  <- droplevels(status_char)
      shift <- if (LT) abs(min(df[[entry_col]], na.rm = TRUE)) + 1e-6 else 0
      df$entry_shift <- if (LT) df[[entry_col]] + shift else 0
      df$exit_shift  <- df[[exit_col]] + shift
      
      dt <- .cif_boot_ci(df, pred, timeStop = "exit_shift", entryCol = if (LT) "entry_shift" else NULL,
                         statusCol = "censor2", nBoot = nBoot)
      pdf(file.path(outDir, sprintf("CIF.%s.%s.pdf", pred, timeOrigin)))
      print(ggplot2::ggplot(dt, ggplot2::aes(time - shift, cif, colour = strata, fill = strata)) +
              ggplot2::geom_step(linewidth = .7) +
              ggplot2::geom_ribbon(ggplot2::aes(ymin = cif.low, ymax = cif.high), alpha = .25, linewidth = 0) +
              ggplot2::theme_light() + ggplot2::labs(x = "Years", y = "Cumulative incidence", colour = pred))
      dev.off()
    }
    
    # Diagnostics ------------------------------------------------------------
    if (diag) {
      cox.z <- survival::cox.zph(multi)
      pdf(file.path(outDir, sprintf("Diag.%s.%s.pdf", pred, timeOrigin)))
      print(survminer::ggcoxzph(cox.z))
      dev.off()
    }
  }
  
  res <- dplyr::bind_rows(res_list)
  invisible(list(results = res, followUp = mf,
                 km_fit = NULL, cif_fit = NULL))
}

# ---- 8. Internals -----------------------------------------------------------
.merge_tvc <- function(df, tv_df, entry, exit, timeOrigin) {
  # Convert a single TVC to counting‑process format via survival::tmerge.
  vname <- unique(tv_df$name)[1]
  tv_df <- tv_df[, c("eid", "start", "stop", "value")]
  names(tv_df)[4] <- vname
  base <- df[, c("eid", entry, exit, "censor")]
  names(base)[match(entry, names(base))] <- "tstart"
  names(base)[match(exit,  names(base))] <- "tstop"
  tdat <- survival::tmerge(base, base, id = eid, tstart = tstart, tstop = tstop)
  tdat <- survival::tmerge(tdat, tv_df, id = eid, change = survtdc(start, stop, value))
  tdat <- dplyr::left_join(tdat, df[, setdiff(names(df), c(entry, exit, "censor"))], by = "eid")
  tdat
}

# ============================================================================
